project_id: '512964'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /src/main/resources/assets/octarine/lang/en_us.json
    translation: /src/main/resources/assets/octarine/lang/%locale_with_underscore%.json
  # books and guides
  - source: /src/main/resources/data/patchouli_books/witches_guide/en_us/**/*.json
    translation: /src/main/resources/data/patchouli_books/witches_guide/%locale_with_underscore%/**/*.json
  - source: /src/main/resources/data/patchouli_books/wizards_guide/en_us/**/*.json
    translation: /src/main/resources/data/patchouli_books/wizards_guide/%locale_with_underscore%/**/*.json
