# The latest versions are available at https://quiltmc.org/en/usage/latest-versions
[versions]
# plugins
spotless = "6.25.0"
kotlin = "2.0.0"

# minecraft
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"

# quilt
quilt_loom = "1.7.3"
quilt_loader = "0.26.1-beta.1"

# mods
quilted_fabric_api = "7.5.0+0.92.2-1.20.1"

[libraries]
# minecraft and quilt
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

# quilt api
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
